version: '3.4'
services:
  client:
    build: 
      context: ./client
      network: host
    ports:
      - '3001:3000'
    stdin_open: true
    depends_on:
      - api
      - social
  social:
    build: 
        context: ./social
        network: host
    ports:
      - '5000:5000'
    depends_on:
      - mongo
  api:
    build: 
        context: ./api
        network: host
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
