version: '3.4'
services:
  ui:
    build: 
      context: ./client
      network: host
    ports:
      - '3000:3000'
    depends_on:
      - api
      - social
  social:
    build: 
        context: ./social
        network: host
    ports:
      - '5000:5000'
    depends_on:
      - mongo
  api:
    build: 
        context: ./api
        network: host
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  mongo:
    image: mongo
    network_mode: host
    ports:
      - '27017:27017'